base-url: api/v1/

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/DEV_TMS
        username: postgres
        password: Zoro11*
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    security:
      auth_header: Authorization
      token_type: Bearer
      secretKey: UF/nq59H6SFHeJl7iSDw+Uqe2vtqgIpEuhc6Pfh7cKCbck3ugSRiWlR3Dp4HmSHrmcmvmDFhCSYicEBjSLndMg==